### ISSUE TITLE
Fatal error when Imagify, Gravity Forms, and the Gravity forms Mailchimp add-on plugins are all enabled and new Mailchimp feed is created

### ISSUE THREAD

**Issue by joejoe04** [wp-media/imagify-plugin#567] opened 2021-06-01 14:28 UTC
**Describe the bug**

User is getting a fatal error when Imagify, Gravity Forms, and the Gravity forms Mailchimp add-on plugins are all enabled and they try to create a new Mailchimp feed.

Here is a link to the error:
https://wp-media.slack.com/archives/C5S1X8WBY/p1622557317001100?thread_ts=1622556682.000600&cid=C5S1X8WBY

Here is the ticket (Error is saved as a note attachment here too):
https://secure.helpscout.net/conversation/1529144472/268038/

**To Reproduce**
1. Enable Imagify, Gravity Forms, and Gravity Forms Mailchimp add-on plugins
2. Attempt to create new Mailchimp feed

**Expected behavior**
The Mailchimp feed should be created without error

**Comment by joejoe04** [comment] 2021-07-06 16:48
Seems it may not only be related to Gravity Forms and Gravity Forms MailChimp add-on. We have a new user not using those with same error message:

https://secure.helpscout.net/conversation/1561895538/276597/

```
E_ERROR בשורה 13 בקובץ /wp-content/plugins/imagify/inc/3rd-party/yoast-seo.php. הודעת שגיאה: Uncaught Error: Call to undefined function get_current_screen() in /wp-content/plugins/imagify/inc/3rd-party/yoast-seo.php:13
Stack trace:
#0 /wp-includes/class-wp-hook.php(292): _imagify_dequeue_yoastseo_script()
#1 /public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(484): WP_Hook->do_action()
#3/wp-includes/script-loader.php(1978): do_action()
#4 /public_html/wp-includes/class-wp-hook.php(292): wp_print_head_scripts()
#5 /wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#6 /wp-includes/plugin.php(484): WP_Hook->do_action()
#7 /wp-includes/general-template.php(3009): do_action()
#8 /wp-content/plugins/gutenberg/build/widgets/blocks/legacy-widget.php(89): wp_head()
#9 /wp-includes/class-wp-hook.php(292): gutenberg_handle_legacy_widget_preview_iframe()
#10 /wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
```

And here is a list of all plugins used:

Imagify
Jetpack
Really Simple CAPTCHA
Really Simple SSL
Redirection
Wordfence Security
WP Mail SMTP
WP Rocket
Yoast SEO premium
Contact form 7
Akismet
Gutenberg

**Comment by iCaspar** [comment] 2021-07-06 21:28
Grooming Notes:

### Reproduced: ❌ 
Cannot reproduce locally with yoast (free version) + gravity forms + gravity forms mailchimp + imagify.
However, seems possible that there are other plugins involved, given the second reported occurance above.

### Root Cause:
The error happens when `get_current_screen()` is not defined -- which may happen if certain plugins, under some conditions, short-circuit the usual wp_admin load cycle.

### Scope for Solution:
We can avoid the fatal error by checking that `get_current_screen()` is defined.
Adding 
```
if ( ! function_exists( 'get_current_screen') ) {
	return;
}
```
at the top of the `_imagify_dequeue_yoastseo_script()` function in `inc/3rd-party/yoast-seo.php` should avoid the fatal error in any case.

### Estimate Effort
[XS]

**Comment by piotrbak** [comment] 2021-07-12 14:54
@iCaspar @Tabrisrp This error could be related to Gutenberg and the Block Widgets feature we were talking about today. The error seems to be the same:
https://github.com/wp-media/imagify-plugin/issues/571

And it's already fixed on Gutenberg side. Should we reach the customers to confirm?

**edit**
The first error is pointing to the Gravity Forms directly, the second is related to Gutenberg... Will try to reproduce it...

**Comment by piotrbak** [comment] 2021-07-14 13:38
I'm not able to reproduce it, but it doesn't affect the Imagify pages and optimization process

**Closed as completed** 2021-07-15 15:19 UTC
Labels: type: bug, severity: major, 3rd party compatibility, effort [XS]
