### ISSUE TITLE
CSS Bug into the media library when adding a post

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#49] opened 2017-02-17 17:14 UTC
![capture d ecran 2017-02-17 a 18 08 35](https://cloud.githubusercontent.com/assets/2565525/23075473/e3057de8-f53c-11e6-8f20-24d255e91d58.png)

**Comment by Screenfeed** [comment] 2017-07-11 14:41
Hi there.
Where are we about this? Does it still happen? How to reproduce? (I couldn't)

**Comment by jbma** [comment] 2017-07-11 15:33
Hi,
More info here : https://secure.helpscout.net/conversation/314230591/32510/?folderId=676702

**Comment by Screenfeed** [comment] 2017-07-11 15:51
Thanks. Reading that, I don't think it's a CSS issue, more like HTML tags that are added again and again (maybe an unclosed tag?). I'll investigate.

**Comment by Screenfeed** [comment] 2017-07-28 12:59
So, apparently it's solved.

**Comment by Screenfeed** [comment] 2017-08-04 12:59
It's back!
![dgxpyibxyaarmdb](https://user-images.githubusercontent.com/1878479/28969609-86447448-7925-11e7-8265-eca835c81e27.jpg)
![dgxpyicxcaaofro](https://user-images.githubusercontent.com/1878479/28969610-8647b2fc-7925-11e7-820c-036ca91c7f01.jpg)

**Comment by creativejuiz** [comment] 2017-08-21 10:23
@Screenfeed Is that the bug "the girl you know" has?
Assign it to me if it's the case, I'll try to reproduce/debug it next time I see her.

**Comment by Screenfeed** [comment] 2017-08-21 12:07
@creativejuiz Yep.

**Comment by iCaspar** [comment] 2021-11-16 17:10
Still can't reproduce. Closing.

**Closed by iCaspar** 2021-11-16 17:10 UTC
Labels: type: bug, severity: minor, can't reproduce, CSS
