### ISSUE TITLE
Exif/meta data are removed when using the option to resize big image

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#27] opened 2016-09-05 09:14 UTC
From : https://wordpress.org/support/topic/resize-and-exif/#post-8133324

By default when an image is resize by WP, all meta data are stripped. This is a GD limitation.
This could be solved by using this class instead https://developer.wordpress.org/reference/classes/wp_image_editor_imagick/ with this filter https://developer.wordpress.org/reference/hooks/image_strip_meta/ and GD as a fallback if Imagick is not available.

**Comment by Tabrisrp** [comment] 2016-09-08 22:33
Imagick is first to be used if available, but the image_strip_meta is set by default to true, so setting it to false should be enough to fix the issue

**Comment by jbma** [comment] 2018-05-25 07:15
We've a user who has the issue : as soon as he enable the resize enabled the exif are removed : https://secure.helpscout.net/conversation/583775326/68662?folderId=676703
I reopen the issue.

**Comment by Screenfeed** [comment] 2018-06-25 22:45
So basically we re-open this issue without knowing if the issue is really back.
Closing.

**Closed** 2018-06-25 22:46 UTC
Labels: Can't reproduce, bug, major
