### ISSUE TITLE
Add Option to Prevent WebP Generation If Larger Than Original Format

### ISSUE THREAD

**Issue by joejoe04** [wp-media/imagify-plugin#550] opened 2021-03-17 13:52 UTC
It is a fairly common issue where users have optimized some amount of images before realizing that many of them are ending up with WebP versions larger than the original format image.

**Potential Solution**
Provide an option in the settings pages to not create WebP if they would be larger than the original format image. 

This could also lead to confusion about why WebP images are not created in some cases. To prevent this confusion, could make this setting disabled by default so it would need to be actively enabled by user.

**Comment by iCaspar** [comment] 2021-03-22 12:16
Duplicate of #510.

**Closed as completed by iCaspar** 2021-03-22 12:16 UTC
Labels: duplicate
