### ISSUE TITLE
Reoptimize image in media library isnot working 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/imagify-plugin#790] opened 2024-02-02 07:26 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Avif commit: https://github.com/wp-media/imagify-plugin/commit/b396de27cda71d9b16e311a0f55f482bebf13380
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When clicking reoptimize with lossless or smart compression, image+thumbnails are removed from the upload folder and not regenerated causing a warning 
`[02-Feb-2024 06:48:10 UTC] PHP Warning:  file_get_contents(/var/www/imagify.rocketlabsqa.ovh/htdocs/wp-content/uploads/2024/02/sea2.jpg): Failed to open stream: No such file or directory in /var/www/imagify.rocketlabsqa.ovh/htdocs/wp-includes/functions.php on line 3332`
and status in media library is 'This media lacks the required metadata and cannot be optimized.'

**To Reproduce**
1. fresh activation of imagify
2. upload image 
3. in the media library click 'reoptimize with lossless compression'

**Expected behavior**
- No warning
- Files updated in upload folder
- Status as same as on trunk 

**Screenshots**

**Additional context**
- It was working fine on the trunk (regression)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by wordpressfan** [comment] 2024-02-19 10:46
When we do the reoptimize process, we try to remove the next gen media files:

Start here:
https://github.com/wp-media/imagify-plugin/blob/de6dc98d592a607b52baa89918d3d3c6b7ee8460/classes/Optimization/Process/AbstractProcess.php#L327

Then here:

https://github.com/wp-media/imagify-plugin/blob/de6dc98d592a607b52baa89918d3d3c6b7ee8460/classes/Optimization/Process/AbstractProcess.php#L1023

Then here:

https://github.com/wp-media/imagify-plugin/blob/de6dc98d592a607b52baa89918d3d3c6b7ee8460/classes/Optimization/Process/AbstractProcess.php#L1581

We try to get the next gen. file path but we pass the `$this->format` which in this case equals `@imagify-avif` OR `@imagify-webp`
as in here:

https://github.com/wp-media/imagify-plugin/blob/de6dc98d592a607b52baa89918d3d3c6b7ee8460/classes/Optimization/Process/AbstractProcess.php#L1639

Then goes here:

https://github.com/wp-media/imagify-plugin/blob/de6dc98d592a607b52baa89918d3d3c6b7ee8460/classes/Optimization/File.php#L781-L791

calling the function `imagify_path_to_next_gen` with the previously mentioned values but we are expecting values like `webp` or `avif`

https://github.com/wp-media/imagify-plugin/blob/ec0bf151a9607b8a5e40daaf9c60a7d912700f2f/inc/functions/common.php#L201-L212

Which means that when reoptimize is triggered we are removing the main image file! not the next gen ones which is catastrophic!

What do u think here?

**Comment by Miraeld** [comment] 2024-02-19 11:48
Ummml, what you are saying seems correct. Changing this function :
``` php
function imagify_path_to_next_gen( $path, string $format ) { 
 	switch ( $format ) { 
 		case 'webp': 
 			$path = $path . '.webp'; 
 			break; 
 		case 'avif': 
 			$path = $path . '.avif'; 
 			break; 
 	} 
  
 	return $path; 
 } 
 ```
 Would probably fix one issue.

**Comment by remyperona** [comment] 2024-02-19 13:56
Good find, now that we have the root cause, let's find the best solution to fix it

**Comment by wordpressfan** [comment] 2024-02-19 14:11
Changing the format inside switch cases in `imagify_path_to_next_gen` would be a solution yes, but will require small changes as this function is called in two places over the code, I'm OK with that solution.

Or we can add another case with the constants `WEBP_SUFFIX` and `AVIF_SUFFIX` beside `webp` and `avif`

**Comment by remyperona** [comment] 2024-02-19 19:45
I think the value passed should be fixed in the `AbstractProcess` class instead

**Comment by Mai-Saad** [comment] 2024-02-22 12:17
No warning now and Files updated in upload folder.
Note: while AVIF is off, now we arenot creating webP while if AVIF was on we create AVIF with reoptimize (will open separate GH about that if it was still there after merging https://github.com/wp-media/imagify-plugin/pull/809

**Comment by Mai-Saad** [comment] 2024-02-23 01:32
> Note: while AVIF is off, now we arenot creating webP while if AVIF was on we create AVIF with reoptimize 

- on https://github.com/wp-media/imagify-plugin/pull/801, we are reoptimizing webP while AVIF is off. But when doing reoptimize lossless while AVIF is enabled, we regenerate AVIF only for thumbnail and not for the main image (**small image**). can you please check @wordpressfan @jeawhanlee 

reoptimize_lossless while AVIF on
![reoptimize_lossless](https://github.com/wp-media/imagify-plugin/assets/76941962/71e2653b-c3bb-4b9a-b4bb-cf399fd0b043)

reoptimize_lossless while AVIF off
![reoptimize_lossless_webp](https://github.com/wp-media/imagify-plugin/assets/76941962/a8a1b42f-2937-488f-8aa3-767cb2c20653)

reoptimize_smart while AVIF on
![reoptimize_smart](https://github.com/wp-media/imagify-plugin/assets/76941962/64d0070e-44e5-4012-bdb5-d079f7323d81)


- Lossless reoptimize, won't create AVIF with **large image** while AVIF is enabled. => may be solved with this https://github.com/wp-media/imagify-plugin/pull/811 (working with webP and for AVIF, generate next-gen will be displayed which mitigate the risk)

**Comment by Mai-Saad** [comment] 2024-02-26 10:59
- creating new issue for 1st point.. for the 2nd point tried another image and it's working fine (initial image was having avif size > original image)

**Closed as completed** 2024-03-06 16:55 UTC
Labels: type: bug, severity: major, priority: high, AVIF
