### ISSUE TITLE
Fix Confusing Display Issues When User Has Infinite Plan and Also One-Time Quota

### ISSUE THREAD

**Issue by joejoe04** [wp-media/imagify-plugin#548] opened 2021-03-17 13:35 UTC
https://secure.helpscout.net/conversation/1437476847/242752
https://secure.helpscout.net/conversation/1428722223/0/
- "You have nn% credit left" displayed based on how much one-time quota is left, which confuses users because they think they should be shown that they have unlimited quota

- In the Bulk Optimization and Settings pages, you get the "You have 0% space credit left" or low quota amount left warnings:

![0credit](https://user-images.githubusercontent.com/45705494/111420985-949c9800-86c2-11eb-9069-68f43e98e513.png)

- Also, the "You have 0% credit left" is displayed if sub-accounts are granted more quota than the amount of one-time quota user has:
<img src="https://i.imgur.com/Tp0QfVi.png">

**Potential Solution**
While users subscribed to Infinite plan, could just have everything show as "100% credit left". If they ever cancel, it could go back to showing how much one-time quota is left.

**Comment by GeekPress** [comment] 2022-10-18 08:17
@joejoe04 I can't reproduce the issue on the plugin. Do we still have it? If so, what are the steps to get the error?

**Comment by joejoe04** [comment] 2022-10-18 12:51
@GeekPress I also can't reproduce anything I mentioned here anymore either. I think this must have been resolved with the recent updates.

**Comment by GeekPress** [comment] 2022-10-18 15:00
> @GeekPress I also can't reproduce anything I mentioned here anymore either. I think this must have been resolved with the recent updates.

Thanks for your feedback.

Then, let's close it for now :D

**Closed as completed by GeekPress** 2022-10-18 15:00 UTC
Labels: type: bug, invalid, needs: grooming, priority: medium
