### ISSUE TITLE
Add filter to change mime types

### ISSUE THREAD

**Issue by nabtron** [wp-media/imagify-plugin#468] opened 2020-01-01 06:07 UTC
Hi. Can you add a filter hook to allow webmasters to add or remove a mime type from the list?

In my opinion, adding following hook in file: inc/functions/attachments.php line 28 will help

`	add_filter("image_type_filter", 10, 1);
`

**Comment by Screenfeed** [comment] 2020-01-06 23:09
Duplicate of #438.

**Closed by Screenfeed** 2020-01-06 23:09 UTC
Labels: duplicate
